language: php

sudo: false

php:
    - 5.2
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - WP_VERSION=master WP_MULTISITE=0 WPDB_DRIVER=mysql
    - WP_VERSION=4.1 WP_MULTISITE=0 WPDB_DRIVER=mysql

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - cd /tmp/wordpress
    - phpunit --group wpdb
